# Generated by Django 5.2.7 on 2025-10-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
        ('customauth', '0003_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
