# Generated by Django 5.2.7 on 2025-10-02 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Anwesende'),
        ),
    ]
