# Generated by Django 5.2.7 on 2025-10-02 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='committees',
            field=models.ManyToManyField(related_name='members', to='customadmin.committee', verbose_name='Gremien'),
        ),
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customadmin.function', verbose_name='Funktion'),
        ),
    ]
