# Generated by Django 5.2.7 on 2025-10-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_alter_person_committees_alter_person_function'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
