# Generated by Django 5.2.7 on 2025-10-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funktion',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='funktion',
            new_name='position',
        ),
    ]
