# Generated by Django 5.2.7 on 2025-10-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0005_rename_funktion_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('basisentschaedigung', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sitzungsgeld', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basis_abgabe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sitzungsabgabe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AddField(
            model_name='user',
            name='funktion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='customauth.funktion'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
