# Generated by Django 5.2.7 on 2025-10-02 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0006_funktion_remove_user_position_user_funktion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('basisentschaedigung', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sitzungsgeld', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('basis_abgabe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sitzungsabgabe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='funktion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geburtsdatum', models.DateField(blank=True, null=True)),
                ('telefonnummer', models.CharField(blank=True, max_length=20)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='customauth.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Funktion',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
