# Generated by Django 5.2.7 on 2025-10-02 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abgabe', models.DecimalField(decimal_places=2, help_text='Abgabe in Euro', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Gremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('funktion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anwesenheit.funktion')),
                ('gremien', models.ManyToManyField(related_name='mitglieder', to='anwesenheit.gremium')),
            ],
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ort', models.CharField(max_length=200)),
                ('datum', models.DateTimeField()),
                ('anwesende', models.ManyToManyField(related_name='termine', to='anwesenheit.person')),
                ('gremium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termine', to='anwesenheit.gremium')),
            ],
        ),
    ]
