# Generated by Django 5.2.7 on 2025-10-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anwesenheit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='termin',
            name='name',
        ),
        migrations.AlterField(
            model_name='termin',
            name='ort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anwesenheit.ort'),
        ),
    ]
