# Generated by Django 5.2.7 on 2025-10-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='attendees',
            field=models.ManyToManyField(related_name='appointments', to='customauth.person', verbose_name='Anwesende'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
