# Generated by Django 5.2.7 on 2025-10-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_alter_person_committees_alter_person_function'),
        ('presence', '0002_alter_appointment_attendees_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
